language: minimal

git:
  depth: false
  quiet: true

services:
  - docker

env:
  global:
    - IMAGE_NAME=diuis/docker-ubuntu-base

script:
  - docker build . -t "$IMAGE_NAME"

before_deploy:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: 
    docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  skip_cleanup: true
  on:
    branch: master
    tags: true