variables:
  dockerId: diuis
  imageName: docker-ubuntu-base

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerhub/dockerPassword) 